name: Daily Data to Redis

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3 AM daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create creds.json file
      run: echo $GOOGLE_SHEET_CREDS > secrets/creds.json
      env:
        GOOGLE_SHEET_CREDS: ${{ secrets.GOOGLE_SHEET_CREDS }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data_to_save.py
      env:
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      run: python data_to_save.py
