name: Daily Data to Redis

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 5 AM daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create creds.json file
      run: |
        mkdir -p secrets
        echo "$GOOGLE_SHEET_CREDS" > secrets/creds.json
        echo "Contents of creds.json:"
        cat secrets/creds.json  # Check the content of the created file
      env:
        GOOGLE_SHEET_CREDS: ${{ secrets.GOOGLE_SHEET_CREDS }}

    - name: Verify creds.json file
      run: |
        if [ -f "secrets/creds.json" ]; then
          echo "creds.json file exists"
        else
          echo "creds.json file does not exist"
          exit 1
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check working directory
      run: |
        echo "Current working directory:"
        pwd
        echo "Contents of the working directory:"
        ls -al

    - name: Check secrets directory
      run: |
        echo "Contents of the secrets directory:"
        ls -al secrets

    - name: Print creds.json contents
      run: cat secrets/creds.json

    - name: Run data_to_save.py
      working-directory: /home/runner/work/DividendDashboardFromScratch/DividendDashboardFromScratch
      env:
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      run: python data_to_save.py
